package org.rotki.mobile.core.protocol

import kotlin.io.encoding.Base64
import kotlin.io.encoding.Base64.PaddingOption
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotEquals

class ProtocolPrimitivesTest {
    @Test
    fun `fixed-width values accept generated bytes and redact themselves`() {
        val deviceSessionId =
            assertIs<ProtocolValueParseOutcome.Accepted<DeviceSessionId>>(
                DeviceSessionId.parse(encodedBytes(size = 32)),
            ).value
        val idempotencyKey =
            assertIs<ProtocolValueParseOutcome.Accepted<IdempotencyKey>>(
                IdempotencyKey.fromBytes(generatedBytes(size = 16)),
            ).value
        val signature =
            assertIs<ProtocolValueParseOutcome.Accepted<P1363Signature>>(
                P1363Signature.fromBytes(validSignatureBytes()),
            ).value
        val pairingId =
            assertIs<ProtocolValueParseOutcome.Accepted<PairingId>>(
                PairingId.parse(encodedBytes(size = 16)),
            ).value
        val pairingCredential =
            assertIs<ProtocolValueParseOutcome.Accepted<PairingCredential>>(
                PairingCredential.parse(encodedBytes(size = 32)),
            ).value
        val challengeId =
            assertIs<ProtocolValueParseOutcome.Accepted<ChallengeId>>(
                ChallengeId.parse(encodedBytes(size = 16)),
            ).value
        val challengeNonce =
            assertIs<ProtocolValueParseOutcome.Accepted<ChallengeNonce>>(
                ChallengeNonce.parse(encodedBytes(size = 32)),
            ).value
        val accessSessionCredential =
            assertIs<ProtocolValueParseOutcome.Accepted<AccessSessionCredential>>(
                AccessSessionCredential.parse(encodedBytes(size = 32)),
            ).value

        assertEquals("DeviceSessionId(redacted)", deviceSessionId.toString())
        assertEquals("IdempotencyKey(redacted)", idempotencyKey.toString())
        assertEquals("P1363Signature(redacted)", signature.toString())
        assertEquals("PairingId(redacted)", pairingId.toString())
        assertEquals("PairingCredential(redacted)", pairingCredential.toString())
        assertEquals("ChallengeId(redacted)", challengeId.toString())
        assertEquals("ChallengeNonce(redacted)", challengeNonce.toString())
        assertEquals("AccessSessionCredential(redacted)", accessSessionCredential.toString())
    }

    @Test
    fun `noncanonical alternate and malformed forms fail closed`() {
        val canonicalDevice = encodedBytes(size = 32)
        assertIs<ProtocolValueParseOutcome.Rejected>(DeviceSessionId.parse("$canonicalDevice="))
        assertIs<ProtocolValueParseOutcome.Rejected>(DeviceSessionId.parse(canonicalDevice.dropLast(1)))
        assertIs<ProtocolValueParseOutcome.Rejected>(
            DeviceSessionId.parse(canonicalDevice.dropLast(1) + "/"),
        )
        assertEquals(
            ProtocolValueRejection.INVALID_SIGNATURE,
            assertIs<ProtocolValueParseOutcome.Rejected>(
                P1363Signature.fromBytes(ByteArray(64)),
            ).reason,
        )
        assertEquals(
            ProtocolValueRejection.INVALID_LENGTH,
            assertIs<ProtocolValueParseOutcome.Rejected>(
                P1363Signature.fromBytes(ByteArray(1_000_000)),
            ).reason,
        )
        assertIs<ProtocolValueParseOutcome.Rejected>(X963PublicKey.fromBytes(ByteArray(65)))
        assertIs<ProtocolValueParseOutcome.Rejected>(
            X963PublicKey.fromBytes(ByteArray(65).also { bytes -> bytes[0] = 0x04 }),
        )
        assertIs<ProtocolValueParseOutcome.Rejected>(IdempotencyKey.fromBytes(ByteArray(15)))
        assertEquals(
            ProtocolValueRejection.INVALID_LENGTH,
            assertIs<ProtocolValueParseOutcome.Rejected>(
                X963PublicKey.fromBytes(ByteArray(1_000_000)),
            ).reason,
        )
    }

    @Test
    fun `byte factories and copies do not retain caller-owned arrays`() {
        val source = generatedBytes(size = 16)
        val key =
            assertIs<ProtocolValueParseOutcome.Accepted<IdempotencyKey>>(
                IdempotencyKey.fromBytes(source),
            ).value
        val expected = key.bytesCopy()
        source.fill(0x7f)

        assertContentEquals(expected, key.bytesCopy())
        assertNotEquals(source.toList(), key.bytesCopy().toList())

        val returnedCopy = key.bytesCopy()
        returnedCopy.fill(0x55)
        assertContentEquals(expected, key.bytesCopy())
        assertEquals(
            key,
            assertIs<ProtocolValueParseOutcome.Accepted<IdempotencyKey>>(
                IdempotencyKey.parse(key.encoded),
            ).value,
        )
    }
}

@OptIn(ExperimentalEncodingApi::class)
private fun encodedBytes(size: Int): String =
    Base64.UrlSafe
        .withPadding(PaddingOption.ABSENT)
        .encode(generatedBytes(size))

private fun generatedBytes(size: Int): ByteArray = ByteArray(size) { index -> (index + 1).toByte() }

private fun validSignatureBytes(): ByteArray =
    ByteArray(64).also { bytes ->
        bytes[31] = 1
        bytes[63] = 1
    }
